export const FETCH_RECIPES_START = "FETCH_RECIPES_START";
export const FETCH_RECIPES_SUCCESS = "FETCH_RECIPES_SUCCESS";
export const FETCH_RECIPES_FAIL = 'FETCH_RECIPES_FAIL';
export const SET_KEY = "SET_KEY";
export const SET_KEY_ERROR = "SET_KEY_ERROR";

// auth
export const SET_USER_AUTH_TYPE = "SET_USER_AUTH_TYPE";
export const USER_AUTH_START = "USER_AUTH_START"
export const USER_AUTH_SUCCESS = "USER_AUTH_SUCCESS"
export const USER_AUTH_FAIL = "USER_AUTH_FAIL"
export const USER_AUTH_LOGOUT = "USER_LOGOUT";
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

//categories
export const FETCH_CATEGORIES_START = "FETCH_CATEGORIES_START";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_FAIL = "FETCH_CATEGORIES_FAIL";

//products
export const FETCH_PRODUCTS_START = "FETCH_PRODUCTS_START";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAIL = "FETCH_PRODUCTS_FAIL";

//products
export const FETCH_UNITS_START = "FETCH_UNITS_START";
export const FETCH_UNITS_SUCCESS = "FETCH_UNITS_SUCCESS";
export const FETCH_UNITS_FAIL = "FETCH_UNITS_FAIL";

//shopping list
export const ADD_TO_SHOPPING_LIST_START = "ADD_TO_SHOPPING_LIST_START";
export const ADD_TO_SHOPPING_LIST_SUCCESS = "ADD_TO_SHOPPING_LIST_SUCCESS";
export const ADD_TO_SHOPPING_LIST_FAIL = "ADD_TO_SHOPPING_LIST_FAIL";
export const FETCH_SHOPPING_LIST_START = "FETCH_SHOPPING_LIST_START";
export const FETCH_SHOPPING_LIST_SUCCESS = "FETCH_SHOPPING_LIST_SUCCESS";
export const FETCH_SHOPPING_LIST_FAIL = "FETCH_SHOPPING_LIST_FAIL";
export const COUNT_SHOPPING_LIST_RECIPES = "COUNT_SHOPPING_LIST_RECIPES";
export const RESET_SL_MESSAGES = "RESET_SL_MESSAGES"

//favorites recipes
export const COUNT_FAVORITE_RECIPES = "COUNT_FAVORITE_RECIPES";
export const FETCH_FAVORITES_START = "FETCH_FAVORITES_START";
export const ADD_TO_FAVORITES_SUCCESS = "ADD_TO_FAVORITES_SUCCESS";
export const ADD_TO_FAVORITES_FAIL = "ADD_TO_FAVORITES_FAIL";
export const RESET_FL_MESSAGES = "RESET_FL_MESSAGES"

//statistics
export const FETCH_RECIPES_BY_CATEGORY_START =
         "FETCH_RECIPES_BY_CATEGORY_START";
export const FETCH_RECIPES_BY_CATEGORY_SUCCESS =
         "FETCH_RECIPES_BY_CATEGORY_SUCCESS";
export const FETCH_RECIPES_BY_CATEGORY_FAIL = "FETCH_RECIPES_BY_CATEGORY_FAIL";
export const COUNT_TOTAL_RECIPES = "COUNT_TOTAL_RECIPES";







