export const FETCH_RECIPES_START = "FETCH_RECIPES_START";
export const FETCH_RECIPES_SUCCESS = "FETCH_RECIPES_SUCCESS";
export const FETCH_RECIPES_FAIL = 'FETCH_RECIPES_FAIL';
export const SET_RECIPES_PER_PAGE = "SET_RECIPES_PER_PAGE";
export const SET_LAST_RECIPE_KEY = "SET_LAST_RECIPE_KEY";
//pagination 
export const COUNT_TOTAL_RECIPES = "COUNT_TOTAL_RECIPES";
export const COUNT_RECIPES_FAIL = "COUNT_RECIPES_FAIL";

